name: CI

on:
  push:
    branches: [main]

jobs:
  Deploy-Action:
    name: CI-Deploy-Action
    runs-on: ubuntu-18.04

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'github-host'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_IP }} >> ~/.ssh/known_hosts
      - uses: actions/checkout@v3
      - run: ssh github@${{ secrets.SSH_IP }} "git checkout && exit"
